### ISSUE TITLE
Check out ng-show for login show/hide

### ISSUE THREAD

**Issue by nakaz** [jeffmon/Message-Bored#1]
Refer to these two pieces of code: https://github.com/jeffmon/Message-Bored/blob/master/public/js/controllers/loginController.js#L8-L9

You're using up to variables to store two different booleans and setting each other on 14&15. 

Sticking with one variable is easier to maintain. 

`ng-if` works great but we can optimize by using a built-in angular directive called `ng-show`: https://docs.angularjs.org/api/ng/directive/ngShow

You can probably see what you can do with these areas of code 
https://github.com/jeffmon/Message-Bored/blob/master/public/index.html#L22

**Comment by jeffmon** [comment]
Refactored using ng-show
