### ISSUE TITLE
Do the angular way of changing location/routes to keep it a SPA

### ISSUE THREAD

**Issue by nakaz** [jeffmon/Message-Bored#2]
Reference: https://github.com/jeffmon/Message-Bored/blob/master/public/js/controllers/registerController.js#L21

While this works. it breaks the SPA environment. It's a full page window reload and you'll lose all the state that the SPA has built (if it has built any). Change routes using the angular way so that it can maintain state and not do full-page reloads. 

Docs: https://docs.angularjs.org/api/ng/service/$location

**Comment by jeffmon** [comment]
Got SPA $location working
